package com.myspace.cursojbpmbasics.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DecisionVista implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "decision")
	private java.lang.Boolean decision;

	public DecisionVista() {
	}

	public java.lang.Boolean getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.Boolean decision) {
		this.decision = decision;
	}

	public DecisionVista(java.lang.Boolean decision) {
		this.decision = decision;
	}

}