package com.myspace.capacitacion_project.modelo.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Costos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Costo")
	private java.lang.String costo;
	@org.kie.api.definition.type.Label(value = "Valor")
	private java.lang.String valor;

	public Costos() {
	}

	public java.lang.String getCosto() {
		return this.costo;
	}

	public void setCosto(java.lang.String costo) {
		this.costo = costo;
	}

	public java.lang.String getValor() {
		return this.valor;
	}

	public void setValor(java.lang.String valor) {
		this.valor = valor;
	}

	public Costos(java.lang.String costo, java.lang.String valor) {
		this.costo = costo;
		this.valor = valor;
	}

}