package com.myspace.capacitacion_project.modelo.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Descripciones implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Descripciones() {
    }




}