package com.myspace.cursojbpmbasics.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Persona")
public class Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Primer Nombre")
	private java.lang.String primerNombre;
	@org.kie.api.definition.type.Label("Segundo Nombre")
	private java.lang.String segundoNombre;
	@org.kie.api.definition.type.Label("Primer Apellido")
	private java.lang.String primerApellido;
	@org.kie.api.definition.type.Label("Segundo Apellido")
	private java.lang.String segundoApellido;

	@org.kie.api.definition.type.Label("Edad")
	private int edad;

	@org.kie.api.definition.type.Label(value = "Tipo ID")
	private java.lang.String tipoid;

	@org.kie.api.definition.type.Label(value = "Numero ID")
	private int numeroid;

	public Persona() {
	}

	public java.lang.String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(java.lang.String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public java.lang.String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(java.lang.String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public java.lang.String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(java.lang.String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public java.lang.String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(java.lang.String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public java.lang.String getTipoid() {
		return this.tipoid;
	}

	public void setTipoid(java.lang.String tipoid) {
		this.tipoid = tipoid;
	}

	public int getNumeroid() {
		return this.numeroid;
	}

	public void setNumeroid(int numeroid) {
		this.numeroid = numeroid;
	}

	public Persona(java.lang.String primerNombre,
			java.lang.String segundoNombre, java.lang.String primerApellido,
			java.lang.String segundoApellido, int edad,
			java.lang.String tipoid, int numeroid) {
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.edad = edad;
		this.tipoid = tipoid;
		this.numeroid = numeroid;
	}

	@Override
	public String toString() {
		return "Persona: "+ getPrimerNombre()+" "+getSegundoNombre()+" " +getPrimerApellido()+" "+getSegundoApellido();
	}
}