package com.myspace.cursojbpmbasics.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class valida implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Validar")
	private java.lang.Boolean validar;

	public valida() {
	}

	public java.lang.Boolean getValidar() {
		return this.validar;
	}

	public void setValidar(java.lang.Boolean validar) {
		this.validar = validar;
	}

	public valida(java.lang.Boolean validar) {
		this.validar = validar;
	}

}